[package]
name = "ffrust"
version = "0.1.0"
authors = ["Zageron <hello@adambryant.ca>"]
edition = "2018"
description = "Rust example for a web based FFR."
repository = "https://github.com/Zageron/ffrust"
license = "AGPL-3.0-only"

[dependencies]
bytemuck = "1.4.1"
winit = "0.23.0"
wgpu = "0.6"
futures = "0.3"

[profile.dev.package."*"]
opt-level = 3
