[package]
name = "ffrust"
version = "0.1.0"
authors = ["Zageron <hello@adambryant.ca>"]
edition = "2018"
description = "Rust example for a web based FFR."
repository = "https://github.com/Zageron/ffrust"
license = "AGPL-3.0-only"

[dependencies]
bytemuck = "1.4.1"
console_error_panic_hook = { version = "0.1.6", optional = true }
console_log = "0.2.0"
env_logger = "0.8.1"
euclid = "0.22.1"
futures = "0.3.7"
log = "0.4.11"
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
specs = { version = "0.16.1", default-features = false, features = ["specs-derive"] }
wasm-bindgen-futures = { version = "0.4.18", optional = true }
web-sys = { version = "=0.3.40", optional = true }
wgpu = "0.6"
winit = { version = "0.23.0", features = ["web-sys", "serde"] }

[profile.dev.package."*"]
opt-level = 2

[features]
default = ["native"]
wasm = [
    "console_error_panic_hook",
    "web-sys",
    "wasm-bindgen-futures",
    "rand/wasm-bindgen",
    "specs/wasm-bindgen",
]
native = ["specs/parallel"]
